### PR TITLE
Adding working loader

### PR DESCRIPTION
**Pull request by ianwalter**
I tried using the loader referenced in FullHuman/purgecss-webpack-plugin#18 but it didn't work and I think it makes much more sense to be under the same org and have the same license as purgecss itself so I just rewrote it from scratch. Sorry there's no tests. I can add them and a Travis config at some point in the future.

### CODE REVIEW

**Comment by ianwalter** [comment]
@jsnanigans @Ffloriel Is there anyone available to take a look at this? Thank you.

**Comment by jsnanigans** [comment]
thanks this is awesome! ill try it out as soon as I have some time

**Comment by ianwalter** [comment]
You can see a working example application here: https://github.com/ianwalter/purgecss-example

**Comment by Ffloriel** [comment]
Looks ok to me :)
Could you add some tests for it? There are some here for the american express loader: https://github.com/americanexpress/purgecss-loader

**Comment by ianwalter** [comment]
@Ffloriel In case you didn't get an alert for it, the tests have been added.

**Review by AhiVT — APPROVED** [review]

**Comment by Ffloriel** [comment]
Oh sorry, I missed the notifications. Thanks for the PR! I'll release to npm soon.

**Pull request merged**
